# Generated by Django 3.2.5 on 2021-07-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210714_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityreading',
            name='date',
        ),
        migrations.RemoveField(
            model_name='temperaturereading',
            name='date',
        ),
    ]
