# Generated by Django 3.2.5 on 2021-07-14 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210714_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidityreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
