# Generated by Django 3.2.5 on 2021-07-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_humidityreading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidityreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
