# Generated by Django 3.2.5 on 2021-07-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_humidityreading_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityreading',
            name='date',
        ),
        migrations.RemoveField(
            model_name='humidityreading',
            name='humidity',
        ),
    ]
