# Generated by Django 3.2.5 on 2021-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210715_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='date',
            field=models.DateTimeField(blank=True, default='2021-07-15T07:09:54'),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='date',
            field=models.DateTimeField(blank=True, default='2021-07-15T07:09:54'),
        ),
    ]
