# Generated by Django 3.2.5 on 2021-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210715_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='date',
            field=models.DateTimeField(blank=True, default='2021-07-16T18:28:13'),
        ),
    ]
