# Generated by Django 3.2.5 on 2021-07-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210717_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='humidity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
