# Generated by Django 3.2.5 on 2021-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210717_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
